import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </div>
  );
};

export const getStaticProps = async (context) => {
  const res = await fetch("https://rickandmortyapi.com/api/character");
  const { result } = await res.json();

  return {
    props: {
      characters: result,
    },
  };
};

export default Home;
